version: '3'
services:
  azure-vote-back:
    platform: linux/amd64
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6380:6380"

  azure-vote-front:
    platform: linux/amd64
    build: ./azure-vote
    image: yashnisar/azure-vote-front:v6-redis
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"
